### ISSUE TITLE
Does not it support TF-GPU version?

### ISSUE THREAD

**Issue by haiyang-tju** [illagrenan/tensorflow-serving-api-python3#4]
I use this command "pip install --upgrade tensorflow-serving-api-python3" to install tf-serving, but it automatically installed the CPU version of Tensorflow, and uninstall my GPU version, why? Does not it support TF-GPU version?

And the command "pip install 'tensorflow-seving-api-python3~=1.7.0'" has the problem: 
`Collecting tensorflow-seving-api-python3~=1.7.0
  Could not find a version that satisfies the requirement tensorflow-seving-api-python3~=1.7.0 (from versions: )
No matching distribution found for tensorflow-seving-api-python3~=1.7.0`

**Comment by haiyang-tju** [comment]
@illagrenan there is a misspelling of the word "serving", not "seving"!!! I just copy it from your page.

But the TF-GPU version question is not solved.

**Comment by illagrenan** [comment]
Hi! This package depends on the non-GPU version of TF (this is the same as the original Python2-only package).

You can install this package this way:

```
pip install tensorflow-serving-api-python3 --no-dependencies
pip install tensorflow-gpu
```
