### ISSUE TITLE
Re-package tensorflow-serving-api==1.9.0 (discussion about future of this package)

### ISSUE THREAD

**Issue by illagrenan** [illagrenan/tensorflow-serving-api-python3#6]
Release: https://pypi.org/project/tensorflow-serving-api/1.9.0rc2/

**Comment by ghego** [comment]
1.9.0 has been out for a while. Is this going to be repackaged?

**Comment by illagrenan** [comment]
I will try to release a new version later today (Thu) or tomorrow (Fri).

**Comment by ghego** [comment]
actually, I was just checking the official package and it seems to be supporting py3 too. have a look: https://pypi.org/project/tensorflow-serving-api/#files

**Comment by illagrenan** [comment]
You're right! That's new. So I think my project is no longer needed. 😄 It looks like `tensorflow-serving-api` supports Python 3 from version `>=1.8.0`.

**Comment by ghego** [comment]
as far as I understand they did release it with tf 1.9 but somehow the `tensorflow_model_server` command is not available. I'm confused..

**Comment by ghego** [comment]
My bad, I needed to update the linux package too. https://www.tensorflow.org/serving/setup#aptget

**Comment by spate141** [comment]
@illagrenan Thank you for all your work! 🎉

**Comment by ghego** [comment]
The official package seems to require `tensorflow` and does not work with `tensorflow-gpu`. @illagrenan thanks for the good work! maybe worth keeping this alive for one more release while they fix the issue?

**Comment by illagrenan** [comment]
@ghego I understand the problem. I have never understood the splitting of the GPU and the non-GPU version of Tensorflow.

You can try this:

```bash
pip install 'tensorflow-serving-api~=1.9.0' --no-dependencies
pip install 'tensorflow-gpu~=1.9.0'
```

**Comment by ghego** [comment]
Thanks that solved the issue. Do you know if it can be done in a requirements file or conda environment.yml ? I don't seem to have found a way to do that.

**Comment by illagrenan** [comment]
Unfortunately, it looks like it is not possible in `requirements.txt`. And I'm not familiar with Conda. 😞 Ref: https://stackoverflow.com/questions/31798280/pass-no-deps-in-pip-requirements-txt

**Comment by illagrenan** [comment]
But it shouldn't be so hard to handle this situation with your build script / Dockerfile. For example, I would do this in Dockerfile:

```Dockerfile
RUN pip install -r requirements.txt
RUN pip uninstall tensorflow-gpu
RUN pip install tensorflow
```
